language: ruby
rvm:
- 2.3.3
before_script:
- git update-index --chmod=+x ./build.sh
- chmod +x ./build.sh
script: "./build.sh"
branches:
  only:
  - jekyll
env:
  global:
  - secure:
  - secure: Z7C10eKB0lpPFzQY7RP8SoqpbHiOBMD68oSwzK8gCd6sRmarraiEQPTFqoZMrT5/ujQVCIagQSYbNeshGZVSN0xY5E2wFy8kWWaTPWHMp3GTWH9bvjIJHhb7fH2vPH2rZImzZWHbeovLKegbyv36a0xWvt+6k0EaPorTF425Ey32hdINaMMmAFERs4HJiT89pqrMvv6QyUKAtoTS4GXELqHl69g+Ief10SIvK9UejUL0ovWfBcARniVVtSmdmcrSfJtNDKAC7ITHHzd6OypMhVEOCJ47L6USeAZVTM6/uo5Yb5CAtckmkPmki0SB5T5G8/YZ3+j6ftCO9F8OADBvdPYKv/z+umUZFdBcuugeLwzZc+RyExjViAgT3HLYJ0uDRlg+bMW3IVaEvv0QYDIk2nnfl/BCUOQXIpw8fYfdgA8EHpZ5WJlUDqlIFujfc388JHxyVACjIWDFWPuNpUp7PbV0A97zs3KWgPu1r0T8FxoOP5y9bOtCsp3dI0uGUN295OWraCGh2eeXe02nB2YSCHn+gKgE6JXJHPgpJhXvuVbUi78I7IwrIW5P13/C8nhwfNCykH3A9LbOXtvL7h3nvbZmQCyugyu1HskWIgRsinQsANijOSXpBvjVF5NzYtyiUfmfYMmgbwNT/4SN87yWfvu16cphIHmhDjNvFM2zCqU=
sudo: false
