name: Umanga Bista
title: UmB
description: Personal website and blog of Umanga Bista
url: "http://bistaumanga.com.np"

# Author info
author_name: Umanga Bista
author_bio: "Machine learninng, Big data and Stream mining enthusiast" 

# External services
github_url: "https://github.com/bistaumanga"
linkedin_url: "https://np.linkedin.com/in/bistaumanga"
researchgate_url: "https://www.researchgate.net/profile/Umanga_Bista"
email: "mail@bistaumanga.com.np"
gravatar: 05710f1aef9f9b4aed9b61381cd625db

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: false

# Site settings
permalink: /blog/:title/
relative_permalinks: false
highlighter: pygments
rel: "canonical"
source: ./
destination: ../master
timezone: Asia/Kathmandu
paginate: 3
destination: _site/blog

## Publications and citations
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_publications
  bibliography: citations.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
