name: Umanga Bista
description: Personal website and blog of Umanga Bista
url: "http://bistaumanga.com.np"

# Author info
author_name: Umanga Bista
author_image_path: /images/author-image.jpg
author_bio: |
    Research Assistant at <a href=http://www.logpoint.com/>LogPoint</a>.<br>
    Formerly, Computer Engineering undergrad at <a href=http://www.ioe.edu.np/>Institute of Engineering, Central Campus</a>.

# External services
github_url: "https://github.com/bistaumanga"
linkedin_url: "https://np.linkedin.com/in/bistaumanga"
researchgate_url: "https://www.researchgate.net/profile/Umanga_Bista"
email: "mail@bistaumanga.com.np"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: false

# Site settings
permalink: /blog/:title/
relative_permalinks: false
highlighter: pygments

## Publications and citations
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_publications
  bibliography: citations.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
